### ISSUE TITLE
Mass assignment vulnerability - security critical fields are added in fillable array

### ISSUE THREAD

**Issue by MHassanSaqib** [rinvex/addresses#42]
The following two fields are not fillable. 

```
        'addressable_id',
        'addressable_type',

```

These two fields are critical and shouldn't be inside the fillable array. A hacker or malicious user can just add two inputs in his form to manipulate other users' information.  If you need to use `create ` or any other mass assignment function that I don't know you have used or not then you can use `forceFill()` for these fields carefully.

**Comment by Omranic** [comment]
Thank you, I understand your concern which is completely valid, however in my opinion (which could be wrong) this is left for developers to handle on the FormRequests validation and data saving process.

I know it shouldn't be allowed in the first place, but in favor to convention over configuration you expect to save all fields on the model when passing it some data, that's why it's been included by default in the model (which you can override by the way and override the $fillable array or even completely change the logic).
